version: '3'

services:
  nextjs:
    build: .
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl.sh:/ssl.sh
    depends_on:
      - nextjs
    entrypoint: ["/bin/bash", "/entrypoint.sh"]
