version: '3.8'

services:
  nextjs:
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production

  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - nextjs
