version: '3.8'

services:
  nextjs1:
    build:
      context: .
    ports:
      - "3001:3000"
    env_file:
      - ./.env.nextjs1

  nextjs2:
    build:
      context: .
    ports:
      - "3002:3000"
    env_file:
      - ./.env.nextjs2

  nextjs3:
    build:
      context: .
    ports:
      - "3003:3000"
    env_file:
      - ./.env.nextjs3

  nextjs4:
    build:
      context: .
    ports:
      - "3004:3000"
    env_file:
      - ./.env.nextjs4

  nextjs5:
    build:
      context: .
    ports:
      - "3005:3000"
    env_file:
      - ./.env.nextjs5
